from enum import Enum


class RejectionCode(str, Enum):
    CLIENT_NOT_ALLOWED = "CLIENT_NOT_ALLOWED"
    MISSING_REQUIRED_METRIC = "MISSING_REQUIRED_METRIC"
    SIGNATURE_INVALID = "SIGNATURE_INVALID"
    ATTESTATION_FAILED = "ATTESTATION_FAILED"
    NONCE_REPLAY = "NONCE_REPLAY"
    DP_BUDGET_EXCEEDED = "DP_BUDGET_EXCEEDED"
    PAYLOAD_TOO_LARGE = "PAYLOAD_TOO_LARGE"
    POISONING_ANOMALY = "POISONING_ANOMALY"
    SEMANTIC_FRAGMENT_INVALID = "SEMANTIC_FRAGMENT_INVALID"
    CONSTRAINT_CLOSURE_FAILED = "CONSTRAINT_CLOSURE_FAILED"
    POLICY_ERROR = "POLICY_ERROR"
